version: '3.8'

services:
  vite_app:
    container_name: vite_react_app
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ./key.pem:/app/key.pem
      - ./cert.pem:/app/cert.pem